import fibraOptica from '../../img/fibra.png'
import velocidad from '../../img/velocidad.png'
import ilimitadoSimetrico from '../../img/simetrica.png'
import fijo from '../../img/fono win.png'
import canalesVivo30 from '../../img/internet.png'
import graba from '../../img/diamante.png'
import conectalo from '../../img/duo.png'
import retrocede from '../../img/gol.png'
import hasta2 from '../../img/multitv.png'
import deporte from '../../img/sports.png'
import llamaPeru from '../../img/peru.png'
import canalesVivo60 from '../../img/tvwin.png'

const Value=['100% fibra óptica','Internet ilimitado y simétrico','Mayor velocidad','Tu teléfono fijo estes donde estés','Llama a todo el Perú','Conéctalo y úsalo','+30 canales en vivo','Graba tu programa favorito','Retrocede en vivo','+60 canales en vivo','Hasta 2 dispositivos en simultáneo','Lo mejor del deporte por DSPORTS','+80 canales en vivo']

const [fibraOpticatxt,ilimitadoSimetricotxt,velocidadtxt,fijotxt,llamaPerutxt,conectalotxt,canalesVivo30txt,grabatxt,retrocedetxt,canalesVivo60txt,hasta2txt,deportetxt,canalesVivo80txt]=Value

export const TrioWinItems=[
{
  /*-----100 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"100Mbps",
  MegasPromo:"200Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 99 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/124",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,

},{
  /*-----150 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"150Mbps",
  MegasPromo:"300Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 119 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/144",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----200 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"200Mbps",
  MegasPromo:"400Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 129 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/154",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----300 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"300Mbps",
  MegasPromo:"600Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 169 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/194",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----600 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"600Mbps",
  Promo:"S/ 254 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/284",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----1000 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"1000Mbps",
  Promo:"S/ 454 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/484",
  Mesh:"Incluye 2 Mesh y McAfee",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
}
]


export const DouGoBasico=[
{
  /*-----100 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"100Mbps",
  MegasPromo:"200Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 134 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/154",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----150 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"150Mbps",
  MegasPromo:"300Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 154 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/174",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----200 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"200Mbps",
  MegasPromo:"400Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 164 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/184",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt

},{
  /*-----300 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"300Mbps",
  MegasPromo:"600Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 204 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/224",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----600 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"600Mbps",
  Promo:"S/ 289 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/314",
  Mesh:"Incluye 2 Mesh y McAfee",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----1000 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"1000Mbps",
  Promo:"S/ 489 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/514",
  Mesh:"Incluye 2 Mesh y McAfee",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo60txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
}
]

export const DouGoFull=[
{
  /*-----100 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"100Mbps",
  MegasPromo:"200Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 156 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/176",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----150 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"150Mbps",
  MegasPromo:"300Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 176 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/196",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----200 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"200Mbps",
  MegasPromo:"400Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 186 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/206",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----300 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"300Mbps",
  MegasPromo:"600Mbps",
  Descripcion:"Duplica tu velocidad x 3 meses",
  Promo:"S/ 226 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/246",
  Mesh:"Incluye 1 Mesh",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----600 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"600Mbps",
  Promo:"S/ 311 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/336",
  Mesh:"Incluye 2 Mesh y McAfee",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
},{
  /*-----1000 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"1000Mbps",
  Promo:"S/ 511 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/536",
  Mesh:"Incluye 2 Mesh y McAfee",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo60,
  txt2Cl1:canalesVivo80txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:deporte,
  txt2Cl3:deportetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt
}
]

export const PlanTrioGamer=[
{
  /*-----100 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"100Mbps",
  Promo:"S/ 129 al mes",
  tiempoPromo:"Precio promo x 3 meses",
  Precio:"Precio regular S/154",  
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----150 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"150Mbps",
  Promo:"S/ 149 al mes",
  tiempoPromo:"Precio promo x 3 meses",
  Precio:"Precio regular S/174",
  Mesh:"Incluye 1 Mesh",  
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----200 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"200Mbps",
  Promo:"S/ 159 al mes",
  tiempoPromo:"Precio promo x 3 meses",
  Precio:"Precio regular S/184",
  Mesh:"Incluye 1 Mesh",  
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
},{
  /*-----300 Mbps-----*/

  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"300Mbps",
  Promo:"S/ 199 al mes",
  tiempoPromo:"Precio promo x 3 meses",
  Precio:"Precio regular S/224",
  Mesh:"Incluye 1 Mesh",  
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,
  img3Cl1:fijo,
  txt3Cl1:fijotxt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,
  img3Cl2:llamaPeru,
  txt3Cl2:llamaPerutxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
  img3Cl3:conectalo,
  txt3Cl3:conectalotxt,
}
]
export const PlanTrioGamerGoBasico=[
  {
  /*-----100 Mbps-----*/
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 164 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/184",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
  /*-----150 Mbps-----*/

    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 184 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/204",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
  /*-----200 Mbps-----*/

    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 194 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/214",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
  /*-----300 Mbps-----*/

    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 234 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/254",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  }
]
export const PlanTrioGamerGoFull=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 186 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/206",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo80txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 206 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/226",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo80txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 216 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/236",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo80txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 256 al mes",
    tiempoPromo:"Precio promo x 3 meses",
    Precio:"Precio regular S/276",
    Mesh:"Incluye 1 Mesh",  
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo80txt,
    img3Cl1:fijo,
    txt3Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
    img3Cl2:llamaPeru,
    txt3Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
    img3Cl3:conectalo,
    txt3Cl3:conectalotxt,
  }
]



export const PlanDuoTV =[
{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"100Mbps",
  MegasPromo:"200Mbps",
  Descripcion:"Duplica tu velocidad x 2 meses",
  Promo:"S/ 89 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/114",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
},{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"150Mbps",
  MegasPromo:"300Mbps",
  Descripcion:"Duplica tu velocidad x 2 meses",
  Promo:"S/ 109 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/134",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
},{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"200Mbps",
  MegasPromo:"400Mbps",
  Descripcion:"Duplica tu velocidad x 2 meses",
  Promo:"S/ 119 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/144",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
},{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  Megas:"300Mbps",
  MegasPromo:"600Mbps",
  Descripcion:"Duplica tu velocidad x 2 meses",
  Promo:"S/ 159 al mes",
  tiempoPromo:"Precio promo x 2 meses",
  Precio:"Precio regular S/184",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
},{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"600Mbps",
  Promo:"S/ 244 al mes",
  Precio:"Precio regular S/274",
  tiempoPromo:"Precio promo x 2 meses",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
},{
  head:"Sin Plazo de permanencia",
  Titulo:"Internet 100% Fibra",
  MegasPromo:"1000Mbps",
  Promo:"S/ 444 al mes",
  Precio:"Precio regular S/474",
  tiempoPromo:"Precio promo x 2 meses",
  img1Cl1:fibraOptica,
  txt1Cl1:fibraOpticatxt,
  img2Cl1:canalesVivo30,
  txt2Cl1:canalesVivo30txt,

  img1Cl2:ilimitadoSimetrico,
  txt1Cl2:ilimitadoSimetricotxt,
  img2Cl2:graba,
  txt2Cl2:grabatxt,

  img1Cl3:velocidad,
  txt1Cl3:velocidadtxt,
  img2Cl3:retrocede,
  txt2Cl3:retrocedetxt,
}
]

export const PlanDuoDGOBasico=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    Megas:"100Mbps",
    MegasPromo:"200Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 124 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/144",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    Megas:"150Mbps",
    MegasPromo:"300Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 144 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/164",
    Mesh:"Incluye 1 Mesh",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    Megas:"200Mbps",
    MegasPromo:"400Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 154 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/174",
    Mesh:"Incluye 1 Mesh",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    Megas:"300Mbps",
    MegasPromo:"600Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 194 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/214",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    MegasPromo:"600Mbps",
    Promo:"S/ 279 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/304",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Básico",
    MegasPromo:"1000Mbps",
    Promo:"S/ 479 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/504",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  }
]

export const PlanDuoDGOFull=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    Megas:"100Mbps",
    MegasPromo:"200Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 146 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/166",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    Megas:"150Mbps",
    MegasPromo:"300Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 166 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/186",
    Mesh:"Incluye 1 Mesh",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    Megas:"200Mbps",
    MegasPromo:"400Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 176 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/196",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    Megas:"300Mbps",
    MegasPromo:"600Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 216 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/236",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    MegasPromo:"600Mbps",
    Promo:"S/ 301 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/326",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + DGO Full",
    MegasPromo:"1000Mbps",
    Promo:"S/ 501 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/526",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  }
]


export const PlanDuoFonoWin=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    Megas:"100Mbps",
    MegasPromo:"200Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 89 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/109",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    Megas:"150Mbps",
    MegasPromo:"300Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 109 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/129",
    Mesh:"Incluye 1 Mesh",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    Megas:"200Mbps",
    MegasPromo:"400Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 119 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/139",
    Mesh:"Incluye 1 Mesh",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    Megas:"300Mbps",
    MegasPromo:"600Mbps",
    Descripcion:"Duplica tu velocidad x 2 meses",
    Promo:"S/ 159 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/179",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    MegasPromo:"600Mbps",
    Promo:"S/ 244 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/269",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra + FONO WIN",
    MegasPromo:"1000Mbps",
    Promo:"S/ 444 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/469",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  }
]

export const PlanDuoGamer=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 119 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/144",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo30txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:graba,
    txt2Cl2:grabatxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:retrocede,
    txt2Cl3:retrocedetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 139 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/164",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo30txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:graba,
    txt2Cl2:grabatxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:retrocede,
    txt2Cl3:retrocedetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 149 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/174",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo30txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:graba,
    txt2Cl2:grabatxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:retrocede,
    txt2Cl3:retrocedetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 189 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/214",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo30,
    txt2Cl1:canalesVivo30txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:graba,
    txt2Cl2:grabatxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:retrocede,
    txt2Cl3:retrocedetxt,
  }
]


export const PlanDuoGamerGoBasico=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 154 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/174",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 174 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/194",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 184 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/204",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 224 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/244",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo60txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  }
]

export const PlanDuoGamerGoFull=[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 176 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/196",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 196 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/216",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 206 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/226",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 246 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/266",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:canalesVivo60,
    txt2Cl1:canalesVivo80txt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:hasta2,
    txt2Cl2:hasta2txt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:deporte,
    txt2Cl3:deportetxt,
  }
]

export const PlanDuoGamerFono =[
  {
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"100Mbps",
    Promo:"S/ 119 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/139",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"150Mbps",
    Promo:"S/ 139 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/159",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"200Mbps",
    Promo:"S/ 149 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/169",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  },{
    head:"Sin Plazo de permanencia",
    Titulo:"Internet 100% Fibra",
    MegasPromo:"300Mbps",
    Promo:"S/ 189 al mes",
    tiempoPromo:"Precio promo x 2 meses",
    Precio:"Precio regular S/209",
    img1Cl1:fibraOptica,
    txt1Cl1:fibraOpticatxt,
    img2Cl1:fijo,
    txt2Cl1:fijotxt,
  
    img1Cl2:ilimitadoSimetrico,
    txt1Cl2:ilimitadoSimetricotxt,
    img2Cl2:llamaPeru,
    txt2Cl2:llamaPerutxt,
  
    img1Cl3:velocidad,
    txt1Cl3:velocidadtxt,
    img2Cl3:conectalo,
    txt2Cl3:conectalotxt,
  }
]